### ISSUE TITLE
Add NumberOfHashtags primitive

### ISSUE THREAD

**Issue by gsheni** [alteryx/nlp_primitives#139]
- Determines the number of hashtags

**Comment by sbadithe** [comment]
If there are multiple consecutive hashtags (i.e. ###hello), then would we count this as 1 hashtag or 3? One one hand it might make sense to count it as one since the primitive is likely to be used in the context of a tweet, but on the other hand it might lead to unexpected behavior from the user's POV.

**Comment by gsheni** [comment]
I would do the option that is easier. This is a first pass for this primitive.

We should look at what makes sense from a machine learning perspective.

This seems like a good first pass:
https://stackoverflow.com/a/49865854

**Comment by sbadithe** [comment]
Sounds good, thanks!
